### ISSUE TITLE
How to modify card text based on a value selected in Dropdown filter?

### ISSUE THREAD

**Issue by Et9797** [mckinsey/vizro#240] opened 2023-12-28 10:31 UTC
### Question

How can I modify the card text based on a value selected in a Dropdown filter?

For example below is how my basic Vizro app looks:

![Screenshot from 2023-12-28 11-25-23](https://github.com/mckinsey/vizro/assets/20364007/edc1751c-c0c6-4752-a73e-505031412d8a)
![Screenshot from 2023-12-28 11-25-42](https://github.com/mckinsey/vizro/assets/20364007/11ae5156-2bc9-4014-b24b-dc9c460fb469)

How can I target my CustomCard to change  text when I select another value in my Merk brand filter?

### Code/Examples

```python
class CustomCard(vm.Card):
    type: Literal['custom_card'] = 'custom_card'

    def build(self):
        card_build_obj = super().build()
        # Overwrite default settings - card_build_obj[self.id] fetches the underlying dcc.Markdown
        card_build_obj[self.id].dangerously_allow_html = True
        card_build_obj[self.id].mathjax = True
        return card_build_obj
    

vm.Page.add_type("components", CustomCard)


@capture("graph")
def chart_daily_bundle_sales_brand(
    data_frame: pd.DataFrame, 
    x: PandasField = None, 
    y: PandasField = None, 
    title: ChartTitle = None
):
    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=data_frame[x].dt.date,
            y=data_frame[y],
            mode="lines",
            name="Absolute aantal",
        )
    )
    fig.update_layout(title=title, title_x=0.25, hovermode="x unified", legend=dict(x=0, y=1.1, traceorder="normal", orientation="h"))
    fig.update_xaxes(type="category", tickangle=55)
    return fig


@capture("graph")
def chart_daily_bts_ratios_brand(
    data_frame: pd.DataFrame,
    x: PandasField = None,
    y: PandasField = None,
    title: ChartTitle = None
):
    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=data_frame[x].dt.date,
            y=data_frame[y],
            mode="lines",
            name="Merk bundle-to-single verhouding"
        )
    )
    fig.update_layout(title=title, title_x=0.25, yaxis_title="%", hovermode="x unified", showlegend=False)
    fig.update_xaxes(type="category", tickangle=55)
    return fig


page_brand = vm.Page(
    title="Merk",
    layout=vm.Layout(
        grid=[
            [0, 1, 2, 3],
            [4, 4, 4, 4],
            [5, 5, 5, 5],
            [6, 6, 6, 6],
        ],
        row_min_height="200px"
    ),
    components=[
        CustomCard(
            text=f"""
                #### Dagelijkse virtuele bundel sales

                Gemiddelde groei in sales 2 maanden vóór en ná de kortingsverhoging:

                **Absoluut** (voor): {mean_virtual_bundle_sales_pre_discount_change}<br>
                **Absoluut** (na): {mean_virtual_bundle_sales_post_post_discount_change}<br>
            """
        ),
        CustomCard(
            text=f"""
                #### Dagelijkse harde bundel sales

                Gemiddelde groei in sales 2 maanden vóór en ná de kortingsverhoging:

                **Absoluut** (voor): {mean_hard_bundle_sales_pre_discount_change}<br>
                **Absoluut** (na): {mean_hard_bundle_sales_post_discount_change}<br>
            """
        ),
        CustomCard(
            text=f"""
                #### Dagelijkse bundel-to-single ratio

                Gemiddelde bundel-to-single ratio 2 maanden vóór en ná de kortingsverhoging:

                **Voor**: {mean_bts_ratio_pre_discount_change}%<br>
                **Na**: {mean_bts_ratio_post_discount_change}%
            """
        ),
        CustomCard(
            text="""
                #### Correctie

                Kortingsverhoging: **2023-10-17**<br>
                Black Friday: **2023-11-17** t/m **11-27** <br>(verwijderd om bias te mijden)
            """
        ),
        vm.Graph(
            id="daily_virtual_bundle_sales_brand",
            figure=chart_daily_bundle_sales_brand(
                ts_daily_vh_bundle_sales_brand_df, 
                x="date", 
                y="quantity_virtual_bundles",
                title="Sold <b>virtual</b> bundles"
            )
        ),
        vm.Graph(
            id="daily_hard_bundle_sales_brand",
            figure=chart_daily_bundle_sales_brand(
                ts_daily_vh_bundle_sales_brand_df, 
                x="date", 
                y="quantity_hard_bundles",
                title="Sold <b>hard</b> bundles 2"
            )
        ),
        vm.Graph(
            id="daily_bts_ratios_brand",
            figure=chart_daily_bts_ratios_brand(
                ts_daily_vh_bundle_sales_brand_df, 
                x="date", 
                y="bts_ratio",
                title="Bundel-to-single ratio",
            )
        ),
    ],
    controls=[
        vm.Filter(column="discount_change", selector=vm.Dropdown(title="Discount change")), 
        vm.Filter(column="brand", selector=vm.Dropdown(title="Merk")),
    ]
)
```

### vizro version

0.1.7

### Python version

3.10

### OS

Linux

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by maxschulz-COL** [comment] 2024-01-03 16:22
@Et9797 Happy New Year and thank you for posting an issue!

Just curious why you closed the issue - did you manage to resolve your question?

**Comment by Et9797** [comment] 2024-01-03 17:21
> @Et9797 Happy New Year and thank you for posting an issue!
> 
> Just curious why you closed the issue - did you manage to resolve your question?

Happy new years. I closed the question because I read the docs of custom actions introduced in v0.1.7, and it seemed what I was looking for, albeit I haven't implemented it yet. Is it currently possible to solve this problem using controk dropdowns and custom actions?

**Comment by maxschulz-COL** [comment] 2024-01-03 17:29
> > @Et9797 Happy New Year and thank you for posting an issue!
> > Just curious why you closed the issue - did you manage to resolve your question?
> 
> Happy new years. I closed the question because I read the docs of custom actions introduced in v0.1.7, and it seemed what I was looking for, albeit I haven't implemented it yet. Is it currently possible to solve this problem using control dropdowns and custom actions?

Yes, if I understand your request correctly, this should be possible. Let us know if it works out, or if you have any questions.

We are always interested in improving the docs, so if I may ask a quick feedback question :) : was it "easy" to find the solution in the docs? If yes, what did you search for? If no, what was misleading?

**Comment by Et9797** [comment] 2024-01-09 14:27
Hi @maxschulz-COL hope all is well,

I have managed to make the vizro Card text dynamically change the way I desire, when selecting different values from the Dropdown selector, using a custom action. Formatting this to the desired format won't be a further problem. 

However, I cannot manage to also make the bar plot and table update when I filter on these categories. Do you perhaps know how I can make it so that it also filters the grouped Bar chart and dash_data_table when I select different options from the Dropdown? My solution so far:

```python
from pathlib import Path

import pandas as pd

import vizro.models as vm
from vizro.tables import dash_data_table
from vizro.models.types import capture
from .custom_card import CustomCard
from . import PACKAGE_DIR_PATH
from .page_category1 import calc_category_percentage_growth_bts_ratio, grouped_barplot_category


"""
`vh_bundle_sales_category2_df` [Schema]:
    category_2                   object
    quantity_virtual_bundles      int64
    quantity_hard_bundles         int64
    quantity_bundles              int64
    quantity_singles              int64
    bts_ratio                   float64
    discount_change            str
"""
vh_bundle_sales_category2_df: pd.DataFrame = pd.read_pickle(Path(PACKAGE_DIR_PATH, "data", "vh_bundle_sales_category2_df.pkl"))


category2_percentage_growth_bts_ratio: dict[str, float] = {}  # Category (str) : % Growth (float)
for category in vh_bundle_sales_category2_df["category_2"].unique():
    category2_percentage_growth_bts_ratio[category] = calc_category_percentage_growth_bts_ratio(vh_bundle_sales_category2_df, 2, category)

print(len(category2_percentage_growth_bts_ratio))

from pprint import pprint

@capture("action")
def custom_action_category_dropdown(data_frame: pd.DataFrame, i: int, dropdown_values: list[str]):
    """Custom action to dynamically changes card text on differently selected category dropdown values."""

    if not dropdown_values:
        text = f"""
            #### Bundle-to-single ratio

            Mean bundel-to-single ratio 2 months pre en and post discount change date.
        """
        return text
    if "ALL" not in dropdown_values:
        categories = [category for category in dropdown_values]
        text = f"""
            ####  Bundle-to-single ratio

            Mean bundel-to-single ratio 2 months before and after discount change:

            #### For each dropdown in `categories` -> dynamically add to card % percentage growth based on category value selected from filter
            #### TEST_X
        """
        return text
    if "ALL" in dropdown_values and len(dropdown_values) > 1:
        categories = [category for category in dropdown_values if category != 'ALL']
        text = f"""
            ####  Bundle-to-single ratio

            Mean bundel-to-single ratio 2 months before and after discount change:

            #### For each dropdown in `categories` -> dynamically add to card % percentage growth based on category value selected from filter
            #### TEST_Y
        """
    else:
        categories = [category for category in data_frame[f"category_{i}"].unique()]
        text = f"""
            ####  Bundle-to-single ratio

            Mean bundel-to-single ratio 2 months before and after discount change:

            #### For each dropdown in `categories` -> dynamically add to card % percentage growth based on category value selected from filter
            #### TEST_Z
        """
    return text


vm.Page.add_type("components", CustomCard)


page_category2 = vm.Page(
    title="Categorie 2",
    layout=vm.Layout(
        grid=[
            [0, 0, 0, 0, 1],
            [0, 0, 0, 0, 2],
            [0, 0, 0, 0, 2],
            [3, 3, 3, 3, 2],
            [3, 3, 3, 3, 2]
        ]
    ),
    components=[
        vm.Graph(
            id="grouped-bar-plot-category2",
            figure=grouped_barplot_category(
                data_frame=vh_bundle_sales_category2_df,
                x="category_2",
                y="bts_ratio",
                title="Grouped bar plot <b>bundel-to-single</b> ratio (Category 2)",
            )
        ),
        CustomCard(
            text="""
                #### Correctie

                Discount Change Date: **2023-10-17**<br>
                Black Friday: **2023-11-17** t/m **11-27**

                \*_To prevent bias Black Friday has ben obmitted from calculations._
            """
        ),
        CustomCard(
            id="bts-ratios-card-category2",
            text=f"""
                #### Bundle-to-single ratio

                Mean bundel-to-single ratio 2 months before and after discount change:
            """
        ),
        vm.Table(figure=dash_data_table(data_frame=vh_bundle_sales_category2_df, filter_action="native", sort_action="native"))
    ],
    controls=[
        vm.Filter(
            column="category_2",
            selector=vm.Dropdown(
                id="dropdown-category2",
                title="Select category",
                actions=[
                    vm.Action(
                        function=custom_action_category_dropdown(vh_bundle_sales_category2_df, 2), 
                        inputs=["dropdown-category2.value"], 
                        outputs=["bts-ratios-card-category2.children"],
                   )
                ]
            )
        )
    ]
    # TODO: filtering graph + table based when selecting different category values in Dropdown selector.
)
```
[Screencast from 09-01-24 15:16:58.webm](https://github.com/mckinsey/vizro/assets/20364007/d321671a-a916-4b74-882f-d93d1057e98a)

**Comment by Et9797** [comment] 2024-01-09 14:42
For reference, commenting out the action in controls, works as expected when filtering.

**Comment by Et9797** [comment] 2024-01-10 13:14
Temp fix I came up with is to add another Dropdown filter

**Comment by maxschulz-COL** [comment] 2024-01-10 13:38
> Temp fix I came up with is to add another Dropdown filter

Good to hear! Let me take a look to see if there are alternative solutions

**Comment by maxschulz-COL** [comment] 2024-01-10 17:25
So, now I had some time to look into it :) 

First of all, great question, you are stress testing one of the latest additions wo Vizro which is great.

As for the specific problem:
- by supplying a custom action to the `Dropdown`, the implicit filtering action gets overwritten.
- this is at the moment the expected behaviour, but may be subject to change in the future, and your question highlights why that would make sense

To solve the problem one has to explicitly add the filtering action back (which could be found in the source code in the `Filter` model). 

Below is an example which I think adresses your issue:

```py
import pandas as pd

import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro._constants import FILTER_ACTION_PREFIX
from vizro.actions import _filter
from vizro.models import Action
from vizro.models.types import MultiValueType, capture


def _filter_isin(series: pd.Series, value: MultiValueType) -> pd.Series:
    return series.isin(value)


@capture("action")
def my_custom_action(dropdown_value):
    """Custom action."""
    print(dropdown_value)
    text = f"The dropdown species is: {dropdown_value}"
    return text


df = px.data.iris()

page = vm.Page(
    title="Example of a custom action with UI inputs and outputs",
    components=[
        vm.Graph(
            id="scatter_chart",
            figure=px.scatter(df, x="sepal_length", y="petal_width", color="species", custom_data=["species"]),
        ),
        vm.Graph(
            id="scatter_chart_2",
            figure=px.scatter(df, x="sepal_length", y="petal_width", color="species"),
        ),
        vm.Card(id="my_card", text="Click on a point on the above graph."),
    ],
    controls=[
        vm.Filter(
            column="species",
            selector=vm.Dropdown(
                id="dropdownA",
                title="Species",
                actions=[
                    Action(
                        function=_filter(
                            filter_column="species",
                            targets=["scatter_chart", "scatter_chart_2"],
                            filter_function=_filter_isin,
                        ),
                        id=f"{FILTER_ACTION_PREFIX}_dropdown",
                    ),
                    Action(
                        function=my_custom_action(),
                        inputs=["dropdownA.value"],
                        outputs=["my_card.children"],
                    ),
                ],
            ),
        )
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()
```

Let me know if that works :)

**Comment by maxschulz-COL** [comment] 2024-01-15 08:28
Closing as now resolved. Do let me know if any more questions arise :)

**Closed** 2024-01-15 08:29 UTC
Labels: Community, Issue: General Question :question:

**Comment by antonymilne** [comment] 2024-01-15 11:03
Just a couple of comments... 🙂 

This is a great question indeed @Et9797, thank you for raising it! Your dashboard looks really cool. I'm just curious whether the schema comment you have `vh_bundle_sales_category2_df` [Schema]: ...` is consumed by any Python package or is just for developers to read?

The above solution with a custom action is definitely a good one. In the future I hope there will be an even better one, which would be to make the `CustomCard` itself directly responsive to filters in the same way that `Graph` and `Table` are. Since you already have a `CustomCard` component, you would do this by adding the `@capture` decorator to your `CustomCard`, something like this:
```
@capture("not_sure_what_this_will_say_yet")
class CustomCard(VizroBaseModel):
    def __call__(self):
        # logic that takes in the value of the filter and modifies self.text
```

---

@maxschulz-COL I thought we already had it set so that the `actions` field would append rather than overwrite in `Filter`/`Parameter`. At least that's what I remember agreeing with @petar-qb quite a while ago. Maybe there's a good reason we did it this way though, but off the top of my head I think we should indeed probably change this. Making `_filter` public might be another possible solution.

**Comment by Et9797** [comment] 2024-01-15 14:34
> is consumed by any Python package or is just for developers to read?

Just for myself.

Thanks for all the help and time put into this package! Vizro is plain amazing and very intuitive. Absolutely recommending this to everyone I know who quickly needs to build a nice looking dashboard 🙂

**Comment by antonymilne** [comment] 2024-01-15 15:00
Thank you very much for your kind comments @Et9797!
